# Forest Fire Prediction – Data Preprocessing

In this notebook, we prepare the Forest Fires dataset for modeling. 
The following preprocessing steps are performed:

1. Remove duplicates
2. Apply log transformation to the target variable
3. Encode categorical variables
4. Scale numerical features
5. Save the cleaned dataset

In [125]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [126]:
#Load the dataset
df = pd.read_csv("forestfires.csv")
df.head()

   X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

We check for duplicate rows and remove them to avoid bias in modeling.

In [111]:
print("Before removing duplicates:", df.shape)
df = df.drop_duplicates()
print("After removing duplicates:", df.shape)

Before removing duplicates: (517, 13)
After removing duplicates: (513, 13)

In [123]:

print("Duplicate rows:", df.duplicated().sum())


df = df.drop_duplicates()
print("Shape after removing duplicates:", df.shape)


print("Missing values per column:\n", df.isnull().sum())

Duplicate rows: 0
Shape after removing duplicates: (513, 28)
Missing values per column:
 X            0
Y            0
FFMC         0
DMC          0
DC           0
ISI          0
temp         0
RH           0
wind         0
rain         0
log_area     0
month_aug    0
month_dec    0
month_feb    0
month_jan    0
month_jul    0
month_jun    0
month_mar    0
month_may    0
month_nov    0
month_oct    0
month_sep    0
day_mon      0
day_sat      0
day_sun      0
day_thu      0
day_tue      0
day_wed      0
dtype: int64

Duplicate rows are removed to ensure data integrity.
Missing values are checked. No missing values were found.

The target variable `area` is highly right-skewed. We apply a log transformation:
log_area = log(1 + area)

In [112]:
df['log_area'] = np.log1p(df['area'])

df = df.drop(columns=['area'])

df.head()

   X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  log_area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0       0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0       0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0       0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2       0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0       0.0

The dataset contains two categorical variables: `month` and `day`.
We use Encoding to convert them to numeric format.

In [113]:
df = pd.get_dummies(df, columns=['month', 'day'], drop_first=True)

df.head()

,X,Y,FFMC,DMC,DC,ISI,temp,RH,wind,rain,...,month_may,month_nov,month_oct,month_sep,day_mon,day_sat,day_sun,day_thu,day_tue,day_wed
0,7,5,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,...,False,False,False,False,False,False,False,False,False,False
1,7,4,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,...,False,False,True,False,False,False,False,False,True,False
2,7,4,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,...,False,False,True,False,False,True,False,False,False,False
3,8,6,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,...,False,False,False,False,False,False,False,False,False,False
4,8,6,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,...,False,False,False,False,False,False,True,False,False,False

Standardizing numerical features ensures they have mean=0 and std=1.
This is important for algorithms sensitive to feature scales.

In [114]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

numerical_cols = df.select_dtypes(include=np.number).columns

df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

df.head()

,X,Y,FFMC,DMC,DC,ISI,temp,RH,wind,rain,...,month_may,month_nov,month_oct,month_sep,day_mon,day_sat,day_sun,day_thu,day_tue,day_wed
0,1.001657,0.569075,-0.801628,-1.322179,-1.837925,-0.858350,-1.835573,0.406971,1.498430,-0.073555,...,False,False,False,False,False,False,False,False,False,False
1,1.001657,-0.244116,-0.006761,-1.178717,0.484659,-0.508323,-0.152432,-0.694428,-1.733018,-0.073555,...,False,False,True,False,False,False,False,False,True,False
2,1.001657,-0.244116,-0.006761,-1.049290,0.556583,-0.508323,-0.736379,-0.694428,-1.510159,-0.073555,...,False,False,True,False,False,True,False,False,False,False
3,1.433101,1.382265,0.191956,-1.211464,-1.905808,-0.005160,-1.818399,3.221658,-0.005865,0.600261,...,False,False,False,False,False,False,False,False,False,False
4,1.433101,1.382265,-0.241608,-0.930777,-1.806003,0.126100,-1.285976,3.344035,-1.231586,-0.073555,...,False,False,False,False,False,False,True,False,False,False

In [115]:
print("Cleaned dataset shape:", df.shape)
print(df.info())

Cleaned dataset shape: (513, 28)
<class 'pandas.core.frame.DataFrame'>
Index: 513 entries, 0 to 516
Data columns (total 28 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   X          513 non-null    float64
 1   Y          513 non-null    float64
 2   FFMC       513 non-null    float64
 3   DMC        513 non-null    float64
 4   DC         513 non-null    float64
 5   ISI        513 non-null    float64
 6   temp       513 non-null    float64
 7   RH         513 non-null    float64
 8   wind       513 non-null    float64
 9   rain       513 non-null    float64
 10  log_area   513 non-null    float64
 11  month_aug  513 non-null    bool
 12  month_dec  513 non-null    bool
 13  month_feb  513 non-null    bool
 14  month_jan  513 non-null    bool
 15  month_jul  513 non-null    bool
 16  month_jun  513 non-null    bool
 17  month_mar  513 non-null    bool
 18  month_may  513 non-null    bool
 19  month_nov  513 non-null    bool
 20  month_oct  513 non-null    bool
 21  month_sep  513 non-null    bool
 22  day_mon    513 non-null    bool
 23  day_sat    513 non-null    bool
 24  day_sun    513 non-null    bool
 25  day_thu    513 non-null    bool
 26  day_tue    513 non-null    bool
 27  day_wed    513 non-null    bool
dtypes: bool(17), float64(11)
memory usage: 56.6 KB
None

In [117]:
df.to_csv("/Users/sa25/Documents/Forest Fires/Forest-Fires/data/forestfires.csv", index=False)
          
print("File saved successfully")

File saved successfully

In [118]:
print("Dataset shape:", df.shape)
print("Clean dataset saved.")

Dataset shape: (513, 28)
Clean dataset saved.

# Data Cleaning

In this notebook, the Forest Fires dataset was prepared for modeling by performing essential data cleaning and preprocessing steps.

1. Removed Duplicate Records
   Any duplicate rows were removed to ensure data integrity and prevent bias in the model.

2. Log Transformation of Target Variable
   The target variable `area` is highly right-skewed. To normalize the distribution and reduce the impact of extreme values, a log transformation was applied:  
   `log_area = log(1 + area)`. The original `area` column was then dropped.

3. Encoded Categorical Variables 
   The categorical features `month` and `day` were converted into numeric format

4. Feature Scaling 
 `StandardScaler` was used, to have a mean of 0 and a standard deviation of 1. 

5. Final Check and Save
   The cleaned dataset was inspected for correct data types, absence of missing values, and appropriate shape, then saved.